### PR TITLE
Bugfix: Repository name can now be a symlink.

### LINKED ISSUE #2: FindFiles() fails if path is a symlink to a directory.
I've downloaded glow (a CLI markdown viewer) and was puzzled why it didn't show the markdown files in a local repo copy of a private repo where I keep markdown notes. That project uses gitcha to read the files and I ended up tracing the problem here.

In FindFilesExcept() the program explicitly checks if the path is a directory and returns an error. Problem is: Path can be a symlink to a directory (or a symlink to a symlink to a directory, you get  the idea).

I wrote a small function to recurse over the entire symlink chain of a given path until it reaches the "bottom" of the chain. I could send you a PR. Please let me know if this is a desirable fix.

### PR DESCRIPTION
**Pull request by marcopaganini**
Fixes #2

### CODE REVIEW

File: gitcha.go [hunk 1]
```diff
@@ -156,3 +157,30 @@ func FindFirstFile(path string, list []string) (SearchResult, error) {
 
 	return SearchResult{}, nil
 }
+
+// deref takes a filename and recurses through symlinks until it
+// reaches the original filemame. There's a hard imposed maximum
+// depth to prevent infinite recursion.
+func deref(filename string) (os.FileInfo, error) {
```
Comment (muesli) [inline gitcha.go:164]: Maybe we should use `filepath.EvalSymlinks` here instead: https://pkg.go.dev/path/filepath#EvalSymlinks

Comment (marcopaganini) [reply gitcha.go]: Thanks for the suggestion. Naturally, I looked for this function for a long time and couldn't find it, just to now see it right there, staring at me in the face. :) Updating PR.

File: gitcha_test.go [hunk 2]
```diff
@@ -29,6 +31,12 @@ func TestGitRepoForPath(t *testing.T) {
 }
 
 func TestFindFiles(t *testing.T) {
+	tlink, err := tempLink(".")
+	if err != nil {
+		t.Error(err)
```
Comment (muesli) [inline gitcha_test.go:36]: This should probably be a `t.Fatal`. If `tempLink` returns an error, we wouldn't want this to continue, especially since we call something like `os.Remove` with an undefined value `tlink` next.

**Comment by marcopaganini** [comment]
Done.

**Comment by muesli** [comment]
@marcopaganini Note my comment on `t.Fatal` above. It seems to still read `t.Error` in the diff.

**Comment by marcopaganini** [comment]
> @marcopaganini Note my comment on `t.Fatal` above. It seems to still read `t.Error` in the diff.

You're completely correct. My mistake here when running git commit (missed the `-a`). Please take another look.

**Comment by muesli** [comment]
Thank you for this contribution! Will release a `v0.2.0` containing this tomorrow.

**Comment by marcopaganini** [comment]
My pleasure.
